server:
  port: 8081
spring:
  application:
    name: Microservice1
  cloud:
    openfeign:
      client:
        config:
          hello:
            url: http://localhost:8082/serviceB/hello
            connect-timeout: 5000
            read-timeout: 5000

